# Generated by Django 5.2.4 on 2025-07-27 05:26

from django.db import migrations
import uuid


def create_default_objects(apps, schema_editor):
    Brand = apps.get_model("vehicles", "Brand")

    Brand.objects.get_or_create(
        name="noname",
        defaults={
            "vehicle_type": "noname",
            "fuel_tank_capacity_liters": 0,
            "load_capacity_kg": 0,
            "seats_number": 0,
            "uuid": uuid.uuid4(),
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_default_objects),
    ]
