global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/rules.yaml

scrape_configs:
  - job_name: 'django_app'
    metrics_path: '/prometheus/metrics'
    static_configs:
      - targets: ['vehicle-accounting:8000']

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']