# Generated by Django 5.2.5 on 2025-08-15 06:53

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0002_create_deafult_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleGPSPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Местоположение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_points', to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Время начала поездки')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания поездки')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='vehicles.vehicle', verbose_name='Автомобиль')),
                ('end_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_ends', to='tracking.vehiclegpspoint', verbose_name='Конечная точка')),
                ('start_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_starts', to='tracking.vehiclegpspoint', verbose_name='Начальная точка')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='vehiclegpspoint',
            index=models.Index(fields=['vehicle', 'created_at'], name='tracking_ve_vehicle_07aaaf_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclegpspoint',
            index=models.Index(fields=['point'], name='tracking_ve_point_98c583_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['vehicle', 'start_time', 'end_time'], name='tracking_tr_vehicle_2da5db_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['uuid'], name='tracking_tr_uuid_842cc7_idx'),
        ),
    ]
