services:  
  gps-service:
    build:
      context: ..
      dockerfile: ./docker/gps-service.Dockerfile
    depends_on:
      - kafka
    volumes:
      - ../gps_service/src/:/app/
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    restart: always