services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ../monitoring/grafana/provisioning:/etc/grafana/provisioning
      
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ../monitoring/prometheus/prometheus_config:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'

  alertmanager:
    restart: always
    depends_on:
      - prometheus
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ../monitoring/prometheus/prometheus_config/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - ../monitoring/prometheus/alert_templates:/etc/alertmanager/templates

volumes:
  influxdb_data:
  grafana_data:
  prometheus_data:
