# Generated by Django 5.1.5 on 2025-02-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_accounting', '0002_manager_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='phone',
            field=models.CharField(default=8939213421234, max_length=20, verbose_name='телефон'),
            preserve_default=False,
        ),
    ]
