# Generated by Django 5.1.5 on 2025-02-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_accounting', '0003_manager_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='phone',
        ),
        migrations.AddField(
            model_name='manager',
            name='is_on_vacation',
            field=models.BooleanField(default=False, verbose_name='в отпуске'),
        ),
    ]
