# Generated by Django 5.1.5 on 2025-01-25 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('sedan', 'Легковой'), ('truck', 'Грузовой'), ('bus', 'Автобус'), ('suv', 'Внедорожник')], max_length=50)),
                ('fuel_tank_capacity_liters', models.PositiveIntegerField(help_text='Объем бака л')),
                ('load_capacity_kg', models.PositiveIntegerField(help_text='Грузоподъемность кг')),
                ('seats_number', models.PositiveIntegerField(help_text='Количество мест')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена')),
                ('year_of_manufacture', models.PositiveIntegerField(verbose_name='год выпуска')),
                ('mileage', models.PositiveIntegerField(verbose_name='пробег')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата внесения в базу')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления в базе')),
                ('car_number', models.CharField(max_length=6, verbose_name='Номер машины')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicle_accounting.brand', verbose_name='бренд')),
            ],
        ),
    ]
