# Generated by Django 5.1.5 on 2025-02-15 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle_accounting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="manager",
            name="brand",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="vehicle_accounting.brand",
                verbose_name="бренд",
            ),
            preserve_default=False,
        ),
    ]
