# Generated by Django 5.1.5 on 2025-02-18 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_accounting', '0002_manager_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='brand',
        ),
    ]
