# Generated by Django 5.1.5 on 2025-01-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_accounting', '0002_alter_vehicle_car_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='car_number',
            field=models.CharField(max_length=6, unique=True, verbose_name='номер машины'),
        ),
    ]
