# Generated by Django 5.1.5 on 2025-01-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_accounting', '0003_alter_vehicle_car_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='название предприятия')),
                ('city', models.CharField(max_length=250, verbose_name='город')),
                ('phone', models.CharField(max_length=20, verbose_name='телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('website', models.URLField(blank=True, verbose_name='веб-сайт')),
            ],
        ),
    ]
