# Generated by Django 5.1.5 on 2025-03-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_accounting', '0003_remove_manager_brand'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['id'], name='vehicle_acc_id_ed80ca_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['id'], name='vehicle_acc_id_aace9b_idx'),
        ),
        migrations.AddIndex(
            model_name='enterprise',
            index=models.Index(fields=['id'], name='vehicle_acc_id_f2a16b_idx'),
        ),
        migrations.AddIndex(
            model_name='manager',
            index=models.Index(fields=['id'], name='vehicle_acc_id_424206_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['id'], name='vehicle_acc_id_d18ae0_idx'),
        ),
    ]
