# Generated by Django 5.1.5 on 2025-01-25 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_accounting', '0004_enterprise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='имя')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='зарплата')),
                ('experience_years', models.PositiveIntegerField(verbose_name='стаж работы (лет)')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='vehicle_accounting.enterprise', verbose_name='предприятие')),
            ],
        ),
    ]
