# Generated by Django 5.1.5 on 2025-03-09 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_accounting', '0004_brand_vehicle_acc_id_ed80ca_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='vehicle_type',
            field=models.CharField(choices=[('noname', 'noname'), ('sedan', 'Легковой'), ('truck', 'Грузовой'), ('bus', 'Автобус'), ('suv', 'Внедорожник')], max_length=50),
        ),
    ]
