# Generated by Django 5.1.5 on 2025-01-25 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_accounting', '0005_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='enterprise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='vehicle_accounting.enterprise', verbose_name='предприятие'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VehicleDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_vehicles', to='vehicle_accounting.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_drivers', to='vehicle_accounting.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='drivers',
            field=models.ManyToManyField(related_name='vehicles', through='vehicle_accounting.VehicleDriver', to='vehicle_accounting.driver', verbose_name='водители'),
        ),
    ]
