# Generated by Django 5.1.5 on 2025-01-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_accounting', '0006_vehicle_enterprise_vehicledriver_vehicle_drivers'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vehicledriver',
            constraint=models.UniqueConstraint(fields=('vehicle', 'driver'), name='unique_vehicle_driver'),
        ),
    ]
