# Generated by Django 5.1.5 on 2025-01-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_accounting', '0007_vehicledriver_unique_vehicle_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledriver',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активный водитель'),
        ),
        migrations.AddConstraint(
            model_name='vehicledriver',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('driver', 'is_active'), name='unique_active_driver'),
        ),
    ]
