# Generated by Django 5.2.1 on 2025-07-20 13:28

from django.db import migrations
import uuid


def create_default_objects(apps, schema_editor):
    Enterprise = apps.get_model("vehicle_accounting", "Enterprise")
    Brand = apps.get_model("vehicle_accounting", "Brand")

    Enterprise.objects.get_or_create(
        name="noname",
        defaults={
            "city": "Default City",
            "phone": "000000000",
            "email": "default@example.com",
            "uuid": uuid.uuid4(),
        },
    )

    Brand.objects.get_or_create(
        name="noname",
        defaults={
            "vehicle_type": "noname",
            "fuel_tank_capacity_liters": 50,
            "load_capacity_kg": 1000,
            "seats_number": 5,
            "uuid": uuid.uuid4(),
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        (
            "vehicle_accounting",
            "0016_alter_enterprise_timezone_alter_vehiclegpspoint_uuid",
        ),
    ]

    operations = [
        migrations.RunPython(create_default_objects),
    ]
