# Generated by Django 5.2.4 on 2025-07-27 05:30

from django.db import migrations
import uuid


def create_default_objects(apps, schema_editor):
    Enterprise = apps.get_model("enterprises", "Enterprise")

    Enterprise.objects.get_or_create(
        name="noname",
        defaults={
            "city": "noname",
            "phone": "000000000",
            "email": "noname@noname.noname",
            "uuid": uuid.uuid4(),
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("enterprises", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_default_objects)]
