name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgis/postgis:16-3.5
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: vehicle_accounting_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          binutils libproj-dev gdal-bin libgdal-dev \
          sqlite3 libsqlite3-mod-spatialite \
          gcc gettext

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up environment variables
      run: |
        echo "IS_DEBUG=True" >> $GITHUB_ENV
        echo "DJANGO_SECRET_KEY=django-insecure-test-key-for-ci" >> $GITHUB_ENV
        echo "GRAPHHOPPER_API_KEY=" >> $GITHUB_ENV
        echo "GEOPIFY_API_KEY=" >> $GITHUB_ENV

    - name: Run migrations
      run: |
        python manage.py migrate --settings=vehicle_accounting.test_settings

    - name: Collect static files
      run: |
        python manage.py collectstatic --noinput

    - name: Run tests
      run: |
        pytest --ds=vehicle_accounting.test_settings tests/
